alias wiki='cd /d/vimwiki'
alias ,e='vim ~/.bashrc'
alias ,o='. ~/.bashrc'
alias ..='cd ..'
alias ...='cd ../..'
alias glog='git log'
alias gn='git number --column'
alias ga='git number add'
alias vn='git number -c vi'
alias dotfiles='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
