alias ..='cd ..'
alias ...='cd ../..'
alias glog='LANG=en_US.UTF-8 git log'
alias gn='LANG=en_US.UTF-8 git number --column'
alias ga='LANG=en_US.UTF-8 git number add'
alias vn='LANG=en_US.UTF-8 git number -c vi'
alias dotfiles='LANG=en_US.UTF-8 git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME number'
alias gd='LANG=en_US.UTF-8 git number diff'
alias gcmsg='LANG=en_US.UTF-8 git commit --message'
alias ba='$EDITOR ~/.bash_aliases; . ~/.bash_aliases'
alias br='$EDITOR ~/.bashrc; . ~/.bashrc'
alias virsh='virsh --connect=qemu:///system'
alias ra=ranger
alias cpanm='cpanm --notest --mirror http://mirrors.ustc.edu.cn/CPAN/'
alias cpmi='cpm install --without-test --mirror http://mirrors.ustc.edu.cn/CPAN/'
alias e='emacs -nw'
alias p='perl -Mfeature=say -MList::Util -MData::Dumper=Dumper -e '\''BEGIN{ *{"main::$_"} = \&{"List::Util::$_"} for @List::Util::EXPORT_OK; sub p{print Dumper(@_)}}'\'''
